
export default [
    { "_id": "Q101",
        "title": "Quiz 1",
        "description": "First quiz of the semester",
        "course": "RS101",
        "quizType": "Practice Quiz",
        "points": 16,
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true, "timeLimit": 20,
        "multipleAttempts": false,
        "showCorrectAnswers": false,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionAfterAnswer": false,
        "dueDate": "2023-01-05",
        "availableDate": "2023-01-05",
        "untilDate": "2023-01-05",
        "published": true
    },
    { "_id": "E101",
        "title": "Exam 1",
        "description": "First exam of the semester",
        "course": "RS101",
        "quizType": "Graded Quiz",
        "points": 25,
        "assignmentGroup": "Exams",
        "shuffleAnswers": true,
        "timeLimit": 20,
        "multipleAttempts": false,
        "showCorrectAnswers": false,
        "accessCode": "402120",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionAfterAnswer": false,
        "dueDate": "2025-01-10",
        "availableDate": "2025-01-10",
        "untilDate": "2026-01-10",
        "published": true
    },
    { "_id": "Q102",
        "title": "Quiz 2",
        "description": "Second quiz of the semester",
        "course": "RS101",
        "quizType": "Graded Quiz",
        "points": 100,
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 20,
        "multipleAttempts": false,
        "showCorrectAnswers": false,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionAfterAnswer": false,
        "dueDate": "2023-01-18",
        "availableDate": "2023-01-18",
        "untilDate": "2023-01-18",
        "published": false
    },
    { "_id": "HW101",
        "title": "HW 1",
        "description": "First homework of the semester",
        "course": "RS101",
        "quizType": "Graded Survey",
        "points": 33,
        "assignmentGroup": "Assignments",
        "shuffleAnswers": true,
        "timeLimit": 20,
        "multipleAttempts": true,
        "showCorrectAnswers": true,
        "accessCode": "",
        "oneQuestionAtATime": false,
        "webcamRequired": false,
        "lockQuestionAfterAnswer": false,
        "dueDate": "2023-01-24",
        "availableDate": "2023-01-22",
        "untilDate": "2023-01-27",
        "published": false
    },
]